spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  mvc:
    hiddenmethod:
      filter:
        enabled: true # DeleteMapping이나 PutMapping을 할 때 사용

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
